
package com.la.northwind_java.mappers;

import java.time.LocalDateTime;
import java.util.List;

import org.mapstruct.AfterMapping;
import org.mapstruct.Mapper;
import org.mapstruct.Mapping;
import org.mapstruct.MappingTarget;

import com.la.northwind_java.dtos.purchaseOrder.PurchaseOrderCreateDTO;
import com.la.northwind_java.dtos.purchaseOrder.PurchaseOrderDTO;
import com.la.northwind_java.dtos.purchaseOrder.PurchaseOrderUpdateDTO;
import com.la.northwind_java.models.Employee;
import com.la.northwind_java.models.PurchaseOrder;
import com.la.northwind_java.models.PurchaseOrderStatus;
import com.la.northwind_java.models.Supplier;




/**
 * Mapper interface for converting between PurchaseOrder entities and DTOs.
 * 
 */


@Mapper(componentModel = "spring")
public interface PurchaseOrderMapper {

	/**
	 * Converts a PurchaseOrder entity to a PurchaseOrderDTO.
	 * Only essential fields from relationships are mapped (e.g., supplier ID, employee name, etc)
	 */
	
	@Mapping(source = "id", target = "id")
	@Mapping(source = "supplier.id", target = "supplierId")
	@Mapping(source = "createdBy.id", target = "createdBy")
	@Mapping(source = "status.id", target = "statusId")
	@Mapping(source = "approvedBy.id", target = "approvedBy")
	@Mapping(source = "submittedBy.id", target = "submittedBy")
	@Mapping(source = "submittedDate", target = "submittedDate")
	@Mapping(source = "creationDate", target = "creationDate")
	@Mapping(source = "expectedDate", target = "expectedDate")
	@Mapping(source = "shippingFee", target = "shippingFee")
	@Mapping(source = "taxes", target = "taxes")
	@Mapping(source = "paymentDate", target = "paymentDate")
	@Mapping(source = "paymentAmount", target = "paymentAmount")
	@Mapping(source = "paymentMethod", target = "paymentMethod")
	@Mapping(source = "notes", target = "notes")
	
	
	
	PurchaseOrderDTO toDTO(PurchaseOrder purchaseOrder);
	
	/**
	 * Creates a new PurchaseOrder entity with values from a PurchaseOrderCreateDTO
	 * Ignores autogenerated fields and related entities.
	 */
	
	@Mapping(target = "id", ignore = true)
	@Mapping(target = "supplier", ignore = true)
	@Mapping(target = "createdBy", ignore = true)
	@Mapping(target = "status", ignore = true)
	@Mapping(target = "approvedBy", ignore = true)
	@Mapping(target = "submittedBy", ignore = true)
	@Mapping(target = "expectedDate", ignore = true)
	
	PurchaseOrder toEntity(PurchaseOrderCreateDTO dto);
	
	/**
	 * Updates an existing PurchaseOrder entity from a PurchaseOrderUpdateDTO.
	 * Does not replace relationships unless explicitly set.
	 */
	
	@Mapping(target = "createdBy", ignore = true)
	@Mapping(target = "approvedBy", ignore = true)
	@Mapping(target = "submittedBy", ignore = true)
	@Mapping(target = "expectedDate", ignore = true)
	@Mapping(target = "supplier", ignore = true)
	@Mapping(target = "status", ignore = true)
	void updateEntity(PurchaseOrderUpdateDTO dto, @MappingTarget PurchaseOrder entity);
	
	List<PurchaseOrderDTO> toDtoList(List<PurchaseOrder> purchaseOrder);
	
	@AfterMapping
	default void setRelations(@MappingTarget PurchaseOrder po, PurchaseOrderCreateDTO dto) {
	    if (dto.getCreatedBy() != null) {
	        Employee created = new Employee();
	        created.setId(dto.getCreatedBy());
	        po.setCreatedBy(created);
	    }

	    if (dto.getApprovedBy() != null) {
	        Employee approved = new Employee();
	        approved.setId(dto.getApprovedBy());
	        po.setApprovedBy(approved);
	    }

	    if (dto.getSupplierId() != null) {
	        Supplier supplier = new Supplier();
	        supplier.setId(dto.getSupplierId());
	        po.setSupplier(supplier);
	    }

	    if (dto.getStatusId() != null) {
	        PurchaseOrderStatus status = new PurchaseOrderStatus();
	        status.setId(dto.getStatusId());
	        po.setStatus(status);
	    }

	    if (dto.getExpectedDate() != null) {
	        po.setExpectedDate(LocalDateTime.from(dto.getExpectedDate().atStartOfDay()));
	    }
	    if (dto.getSubmittedBy() != null) {
	        Employee submitted = new Employee();
	        submitted.setId(dto.getSubmittedBy());
	        po.setSubmittedBy(submitted);
	    }
	}
	
	/**
	 * Normalize fields after mapping(triming strings)
	 */
	@AfterMapping
	default void normalize(@MappingTarget PurchaseOrder po) {
		if(po.getPaymentMethod() != null) {
			po.setPaymentMethod(po.getPaymentMethod().trim());
		}
		if(po.getNotes() != null) {
			po.setNotes(po.getNotes().trim());
		}
		
	}
	
	
	
	
}
